<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWXwjT4y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWXwjT4y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWXwjT4y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWXwjT4y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWXwjT4y\App_KernelDevDebugContainer([
    'container.build_hash' => 'WXwjT4y',
    'container.build_id' => '7b1e47d9',
    'container.build_time' => 1656678115,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWXwjT4y');
